### ISSUE TITLE
Colour negative conversion throws an error

### ISSUE THREAD

**Issue by sjaakluthart** [Signynt/signynts-darkroom-shortcut#7]
I get the following error when trying to convert the example negative found in this repository's README. Black and white conversion however does work.

```
The action “Run Shell Script” encountered an error: “convert: For function 'min' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: For function 'max' expected 2 arguments, found too few (0) at '' @ error/fx.c/GetFunction/1857.
convert: Expected operand at '/)^(1/2.15))*Quantum...' @ error/fx.c/GetOperand/2298.
convert: Empty expression in parentheses at '/)^(1/2.15))*Quantum...' @ error/fx.c/GetOperand/2033.
convert: Empty expression in parentheses at '/)^(1/2.15))*Quantum...' @ error/fx.c/GetOperand/2033.
convert: Expected operand at '/)/log(/)' @ error/fx.c/GetOperand/2298.
convert: For function 'log' expected 1 arguments, found too few (0) at '/)/log(/)' @ error/fx.c/GetFunction/1857.
convert: Expected operand at '/)/log(/)' @ error/fx.c/GetOperand/2298.
convert: For function 'log' expected 1 arguments, found too few (0) at '/)/log(/)' @ error/fx.c/GetFunction/1857.
convert: Empty expression in parentheses at '/)^(1/2.15))*Quantum...' @ error/fx.c/
```

I've confirmed that I installed the required dependencies correctly, I can run autocolor, autolevel and negfix8 in my terminal.

I'm running this on a 2012 MacBook Pro on MacOS 10.15.7.

**Comment by Signynt** [comment]
Sorry for such a late reply!
That's a strange issue I haven't seen before... Can you confirm for me that you can also run imagemagick in the terminal?

**Comment by sjaakluthart** [comment]
Yes I can run imagemagick in my terminal

**Comment by Signynt** [comment]
Hey, I finally figured this issue out. Something seems to have broken _negfix8_ in the newer _imagemagick_ versions, meaning you have to downgrade to an older version for it to work.
Assuming you already have _imagemagick_ installed downgrade to v6 like this:
1. run `brew install imagemagick@6`
2. run `brew link --overwrite imagemagick@6`
3. You'll probably get a suggestion by brew to run something like `echo 'export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"' >> ~/.zshrc`

That should fix any issues like the one you had where _negfix8_ wouldn't work.
If you're using the IR version of my script you'll need to download the [latest release](https://github.com/Signynt/signynts-darkroom-shortcut/releases/tag/v1.7), since I had to make some changes to make things work with _imagemagick@6_.

Give it a go and let me know if it works for you!

**Comment by sjaakluthart** [comment]
Thanks a lot! I'll try your fix and will let you know how I get on 😄

**Comment by sjaakluthart** [comment]
It works! 🥳
